// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffOrderService.proto

package grpc.ca.order;

public final class OrderService {
  private OrderService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderQueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderQueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderQueryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderUpdateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027staffOrderService.proto\"\023\n\021orderQueryR" +
      "equest\"-\n\022orderQueryResponse\022\027\n\017response" +
      "Message\030\001 \001(\t\"G\n\022orderUpdateRequest\022\017\n\007o" +
      "rderId\030\001 \001(\r\022\021\n\torderName\030\002 \001(\t\022\r\n\005price" +
      "\030\003 \001(\002\".\n\023orderUpdateResponse\022\027\n\017respons" +
      "eMessage\030\001 \001(\t2\204\001\n\013UserService\0227\n\norderQ" +
      "uery\022\022.orderQueryRequest\032\023.orderQueryRes" +
      "ponse\"\000\022<\n\torderEdit\022\023.orderUpdateReques" +
      "t\032\024.orderUpdateResponse\"\000(\0010\001B\037\n\rgrpc.ca" +
      ".orderB\014OrderServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_orderQueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orderQueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderQueryRequest_descriptor,
        new java.lang.String[] { });
    internal_static_orderQueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_orderQueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderQueryResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
    internal_static_orderUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_orderUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderUpdateRequest_descriptor,
        new java.lang.String[] { "OrderId", "OrderName", "Price", });
    internal_static_orderUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_orderUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderUpdateResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
