// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffOrderService.proto

package grpc.ca.order;

public interface orderUpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orderUpdateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
