// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffOrderService.proto

package grpc.ca.order;

public interface orderUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orderUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 orderId = 1;</code>
   */
  int getOrderId();

  /**
   * <code>string orderName = 2;</code>
   */
  java.lang.String getOrderName();
  /**
   * <code>string orderName = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrderNameBytes();

  /**
   * <code>float price = 3;</code>
   */
  float getPrice();
}
