// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffOrderService.proto

package grpc.ca.order;

public interface orderQueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orderQueryRequest)
    com.google.protobuf.MessageOrBuilder {
}
