// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffLoginService.proto

package grpc.ca.loginService;

public interface CheckoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CheckoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string LogoutTime = 1;</code>
   */
  java.lang.String getLogoutTime();
  /**
   * <code>string LogoutTime = 1;</code>
   */
  com.google.protobuf.ByteString
      getLogoutTimeBytes();
}
