// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffLoginService.proto

package grpc.ca.loginService;

public interface CheckinRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CheckinRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string loginTime = 1;</code>
   */
  java.lang.String getLoginTime();
  /**
   * <code>string loginTime = 1;</code>
   */
  com.google.protobuf.ByteString
      getLoginTimeBytes();
}
