// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffLoginService.proto

package grpc.ca.loginService;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
