// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffLoginService.proto

package grpc.ca.loginService;

public interface StampOutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StampOutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
