// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffLoginService.proto

package grpc.ca.loginService;

public interface StampOutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StampOutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
