// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffLoginService.proto

package grpc.ca.loginService;

public interface StampInResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StampInResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 2;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
