// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffLoginService.proto

package grpc.ca.loginService;

public final class UserServiceImpl {
  private UserServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogoutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckinRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckinRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckinResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckinResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckoutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027staffLoginService.proto\"2\n\014LoginReques" +
      "t\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\">\n" +
      "\rLoginResponse\022\027\n\017responseMessage\030\001 \001(\t\022" +
      "\024\n\014responseCode\030\002 \001(\005\"!\n\rLogoutRequest\022\020" +
      "\n\010username\030\001 \001(\t\"?\n\016LogoutResponse\022\027\n\017re" +
      "sponseMessage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(" +
      "\005\"#\n\016CheckinRequest\022\021\n\tloginTime\030\001 \001(\t\"*" +
      "\n\017CheckinResponse\022\027\n\017responseMessage\030\001 \001" +
      "(\t\"%\n\017CheckoutRequest\022\022\n\nLogoutTime\030\001 \001(" +
      "\t\"+\n\020CheckoutResponse\022\027\n\017responseMessage" +
      "\030\001 \001(\t\"\007\n\005Empty2\306\001\n\013UserService\022(\n\005login" +
      "\022\r.LoginRequest\032\016.LoginResponse\"\000\022+\n\006log" +
      "out\022\016.LogoutRequest\032\017.LogoutResponse\"\000\022-" +
      "\n\007checkin\022\017.CheckinRequest\032\017.LogoutRespo" +
      "nse\"\000\0221\n\010checkout\022\020.CheckoutRequest\032\021.Ch" +
      "eckoutResponse\"\000B)\n\024grpc.ca.loginService" +
      "B\017UserServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogoutRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_LogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogoutResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_CheckinRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CheckinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckinRequest_descriptor,
        new java.lang.String[] { "LoginTime", });
    internal_static_CheckinResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CheckinResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckinResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
    internal_static_CheckoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_CheckoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckoutRequest_descriptor,
        new java.lang.String[] { "LogoutTime", });
    internal_static_CheckoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_CheckoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckoutResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
