// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffEmailService.proto

package grpc.ca.mail;

public interface agendaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agendaRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
