// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffEmailService.proto

package grpc.ca.mail;

public interface StaffMailResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StaffMailResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
