// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffEmailService.proto

package grpc.ca.mail;

public final class StaffMailImpl {
  private StaffMailImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AgendaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AgendaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AgendaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AgendaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StaffMailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StaffMailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StaffMailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StaffMailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027staffEmailService.proto\"!\n\rAgendaReque" +
      "st\022\020\n\010username\030\001 \001(\t\")\n\016AgendaResponse\022\027" +
      "\n\017responseMessage\030\001 \001(\t\"$\n\020StaffMailRequ" +
      "est\022\020\n\010username\030\001 \001(\t\",\n\021StaffMailRespon" +
      "se\022\027\n\017responseMessage\030\001 \001(\t2y\n\013UserServi" +
      "ce\0222\n\013staffAgenda\022\016.AgendaRequest\032\017.Agen" +
      "daResponse\"\000(\001\0226\n\tstaffMail\022\021.StaffMailR" +
      "equest\032\022.StaffMailResponse\"\0000\001B\037\n\014grpc.c" +
      "a.mailB\rStaffMailImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AgendaRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AgendaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AgendaRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_AgendaResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AgendaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AgendaResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
    internal_static_StaffMailRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StaffMailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StaffMailRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_StaffMailResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_StaffMailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StaffMailResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
