// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffEmailService.proto

package grpc.ca.mail;

public final class StaffMailImpl {
  private StaffMailImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_staffMailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_staffMailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_staffMailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_staffMailResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containsString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containsString_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027staffEmailService.proto\"$\n\020staffMailRe" +
      "quest\022\020\n\010username\030\001 \001(\t\",\n\021staffMailResp" +
      "onse\022\027\n\017responseMessage\030\001 \001(\t\"%\n\016contain" +
      "sString\022\023\n\013firstString\030\001 \001(\t2z\n\013UserServ" +
      "ice\0226\n\tstaffMail\022\021.staffMailRequest\032\022.st" +
      "affMailResponse\"\0000\001\0223\n\013staffAgenda\022\017.con" +
      "tainsString\032\017.containsString\"\000(\001B\037\n\014grpc" +
      ".ca.mailB\rStaffMailImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_staffMailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_staffMailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_staffMailRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_staffMailResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_staffMailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_staffMailResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
    internal_static_containsString_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_containsString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containsString_descriptor,
        new java.lang.String[] { "FirstString", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
